# dtdinstaller level configuration makefile 
 
MAKEFILE = ${EPOCROOT}/sf/app/homescreentools/dtdinstaller/makefile

# Place the first target as the default target which is executed from this level 
dtdinstaller_all :: dtdinstaller_config
  
include include_template.mk